spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      routes:
        - id: path_route
          uri: http://localhost:8101
          predicates:
            - Path=/api/**
  application:
    name: yy-api-gateway
server:
  port: 8012
logging:
  level:
    root: DEBUG
dubbo:
  registry:
    address: nacos://localhost:8848
    register-mode: instance
  protocol:
    port: 20881