spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
  application:
    name: yy-api-gateway
server:
  port: 8012
logging:
  level:
    root: DEBUG
dubbo:
  registry:
    address: nacos://localhost:8848
    register-mode: instance